### ISSUE TITLE
need graph on openweather 

### ISSUE THREAD

**Issue by sammcgrail** [sammcgrail/radarplot#5]
a simple line graph of the temperature for the 24 hour forecast should be added to the openweather api page.

**Comment by sammcgrail** [comment]
recommending using chartjs (very easy react integration, but sometimes difficult with version 2.9 vs version 3 - I've done it in version 2.9 but wanna do version 3 if possible) 

I wanna avoid using raw d3, avoid using svg, and use something that implements the html5 canvas api.

**Comment by br-ndt** [comment]
One path you could take to achieve this is to pull the weather data from the `LocationContext` using `useLocation()` (checkout `TodayWeather` for an example) and then mapping that data into a format that chartjs likes.

Then a graph component could either receive that data as props, or it could do the derivation/mapping itself
