### ISSUE TITLE
add emojis for weather description

### ISSUE THREAD

**Issue by sammcgrail** [sammcgrail/radarplot#6]
on openweather api, add emojis for weather description. This will require looking into all the weather types .descriptions, and coming up with either basic emoji or fonticons or similar for each one.

**Comment by vanadgir** [comment]
Take a look at [this](https://github.com/vanadgir/fill4/blob/main/src/components/DateTime.js) from one of my projects where I use openweather to grab weather data based on (lat, lon).  I use it to grab the description (sunny, cloudy, rainy), the icon (small png file), the name of the location, and the temperature in F. I'll work on implementing this soon

**Comment by sammcgrail** [comment]
@MichaelJOHare take a look at this, varuns gonna try this one 

example here
 
https://www.varun.pro/fill4/

accept location and check the bottom bar.

**Comment by br-ndt** [comment]
As Varun noted, the OpenWeather data set contains icons for each weather description type. We could either map those to our own emoji, or simply use theirs as Varun did ([here's another example](https://github.com/br-ndt/outThere/blob/main/packages/client/src/components/DayOfWeek/DayOfWeek.tsx))
